# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_GRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hello_GRPC.proto\x12\x07grpcLab\")\n\x0cHelloGrpcReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\" \n\x0eHelloGrpcReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"\xc7\x01\n\x10HelloTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\x12\x35\n\x06number\x18\x04 \x03(\x0b\x32%.grpcLab.HelloTestRequest.NumberEntry\x1aS\n\x0bNumberEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.grpcLab.HelloTestRequestNumberValue:\x02\x38\x01\"K\n\x1bHelloTestRequestNumberValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x11\n\tis_active\x18\x03 \x01(\x08\"\x13\n\x11HelloTestResponse\"+\n\x1bTestClientRecvStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientRecvStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x1bTestClientSendStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"/\n\x1dTestClientScendStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xe2\x02\n\x04\x42ili\x12=\n\tHelloGrpc\x12\x15.grpcLab.HelloGrpcReq\x1a\x17.grpcLab.HelloGrpcReply\"\x00\x12H\n\tHelloTest\x12\x19.grpcLab.HelloTestRequest\x1a\x1a.grpcLab.HelloTestResponse\"\x00(\x01\x30\x01\x12g\n\x14TestClientRecvStream\x12$.grpcLab.TestClientRecvStreamRequest\x1a%.grpcLab.TestClientRecvStreamResponse\"\x00\x30\x01\x12h\n\x14TestClientSendStream\x12$.grpcLab.TestClientSendStreamRequest\x1a&.grpcLab.TestClientScendStreamResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_GRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _HELLOTESTREQUEST_NUMBERENTRY._options = None
  _HELLOTESTREQUEST_NUMBERENTRY._serialized_options = b'8\001'
  _globals['_HELLOGRPCREQ']._serialized_start=29
  _globals['_HELLOGRPCREQ']._serialized_end=70
  _globals['_HELLOGRPCREPLY']._serialized_start=72
  _globals['_HELLOGRPCREPLY']._serialized_end=104
  _globals['_HELLOTESTREQUEST']._serialized_start=107
  _globals['_HELLOTESTREQUEST']._serialized_end=306
  _globals['_HELLOTESTREQUEST_NUMBERENTRY']._serialized_start=223
  _globals['_HELLOTESTREQUEST_NUMBERENTRY']._serialized_end=306
  _globals['_HELLOTESTREQUESTNUMBERVALUE']._serialized_start=308
  _globals['_HELLOTESTREQUESTNUMBERVALUE']._serialized_end=383
  _globals['_HELLOTESTRESPONSE']._serialized_start=385
  _globals['_HELLOTESTRESPONSE']._serialized_end=404
  _globals['_TESTCLIENTRECVSTREAMREQUEST']._serialized_start=406
  _globals['_TESTCLIENTRECVSTREAMREQUEST']._serialized_end=449
  _globals['_TESTCLIENTRECVSTREAMRESPONSE']._serialized_start=451
  _globals['_TESTCLIENTRECVSTREAMRESPONSE']._serialized_end=497
  _globals['_TESTCLIENTSENDSTREAMREQUEST']._serialized_start=499
  _globals['_TESTCLIENTSENDSTREAMREQUEST']._serialized_end=542
  _globals['_TESTCLIENTSCENDSTREAMRESPONSE']._serialized_start=544
  _globals['_TESTCLIENTSCENDSTREAMRESPONSE']._serialized_end=591
  _globals['_BILI']._serialized_start=594
  _globals['_BILI']._serialized_end=948
# @@protoc_insertion_point(module_scope)
