# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_GRPC_pb2 as hello__GRPC__pb2


class Test_StreamStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListFeatures = channel.unary_stream(
                '/test_stream.Test_Stream/ListFeatures',
                request_serializer=hello__GRPC__pb2.Number.SerializeToString,
                response_deserializer=hello__GRPC__pb2.Reply.FromString,
                )


class Test_StreamServicer(object):
    """Interface exported by the server.
    """

    def ListFeatures(self, request, context):
        """A server-to-client streaming RPC.
        rpc ListFeatures(Rectangle) returns (stream Feature) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Test_StreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListFeatures': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFeatures,
                    request_deserializer=hello__GRPC__pb2.Number.FromString,
                    response_serializer=hello__GRPC__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test_stream.Test_Stream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Test_Stream(object):
    """Interface exported by the server.
    """

    @staticmethod
    def ListFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/test_stream.Test_Stream/ListFeatures',
            hello__GRPC__pb2.Number.SerializeToString,
            hello__GRPC__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
