# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_GRPC_pb2 as protocol_dot_hello__GRPC__pb2


class BiliStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloGrpc = channel.unary_unary(
                '/grpcLab.Bili/HelloGrpc',
                request_serializer=protocol_dot_hello__GRPC__pb2.HelloGrpcReq.SerializeToString,
                response_deserializer=protocol_dot_hello__GRPC__pb2.HelloGrpcReply.FromString,
                )


class BiliServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HelloGrpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BiliServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloGrpc': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloGrpc,
                    request_deserializer=protocol_dot_hello__GRPC__pb2.HelloGrpcReq.FromString,
                    response_serializer=protocol_dot_hello__GRPC__pb2.HelloGrpcReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcLab.Bili', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bili(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HelloGrpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcLab.Bili/HelloGrpc',
            protocol_dot_hello__GRPC__pb2.HelloGrpcReq.SerializeToString,
            protocol_dot_hello__GRPC__pb2.HelloGrpcReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
